In [ ]:
import tensorflow as tf


In [ ]:
tensor_1= tf.constant([[1,2],[3,4]])
tensor_2= tf.constant([[5,6],[7,8]])
print("Tensor 1:\n", tensor_1)
print("Tensor_2:\n",tensor_2)

Tensor 1:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Tensor_2:
 tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)


In [ ]:
add =tf.add(tensor_1,tensor_2)
sub= tf.subtract(tensor_1,tensor_2)
mul= tf.multiply(tensor_1,tensor_2)
matmul= tf.matmul(tensor_1,tensor_2)
print("Addition:\n",add)
print("subtraction:\n",sub)
print("Element-wise Multiplication:\n",matmul)
print("Matrix Multiplication:\n",matmul)


Addition:
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
subtraction:
 tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)
Element-wise Multiplication:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
Matrix Multiplication:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [ ]:
tensor_3= tf.constant([1,2,3,4,5,6])
reshaped= tf.reshape(tensor_3,[2,3])
sliced= reshaped[:,1:]
print("Reshaped Tensor:\n", reshaped)
print("sliced Tensor:\n", sliced)

Reshaped Tensor:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
sliced Tensor:
 tf.Tensor(
[[2 3]
 [5 6]], shape=(2, 2), dtype=int32)


In [ ]:
float_tensor= tf.cast(tensor_1,dtype =tf.float32)
print("Float Tensor:\n",float_tensor)

Float Tensor:
 tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


In [ ]:
var= tf.Variable([[1,2],[3,4]])
var.assign_add([[10,10],[10,10]])
print("Updated Variable:\n",var)

Updated Variable:
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>


In [ ]:
print("Shape of tensor_1:", tensor_1.shape)
print("Data type of tensor_1:", tensor_1.dtype)

Shape of tensor_1: (2, 2)
Data type of tensor_1: <dtype: 'int32'>
